### ISSUE TITLE
Provide examples how to launch with several JDKs

### ISSUE THREAD

**Issue by apupier** [CircleCI-Public/maven-orb#15]
**Is your feature request related to a problem? Please describe.**

it is mentioned that `executors` have `tag` parameter https://circleci.com/developer/orbs/orb/circleci/maven#executors but it doesn't provide an example on how to use it. Especially when trying to laucnh against several jdks.

**Describe the solution you'd like**

a new example in https://circleci.com/developer/orbs/orb/circleci/maven#usage-examples

**Describe alternatives you've considered**

**Additional context**
I'm unable to configure it so cannot provide a Pull Request :'(

**Comment by neirfeno** [comment]
@apupier I have just spent an hour or so trying every combination under the sun for this, finally hit the right config:

```workflows:
  maven_test:
    jobs:
      - maven/test:
          executor:
            name: maven/default
              tag: "14.0"
```
I found this from an example that was `name: docker/docker` and running it complained that there was no orb "docker", so it seems that the `x/y` format is `<orb>/<value>`. Since the name is "default", I guessed at this format.

Unfortunately it seems that most of the Orb based documentation is focused around creating new Orbs rather than consuming them.

Anyway, hope this helps you out.
